"""Build the bundled single-word dictionary; no downloads or work happen at runtime.

Source: wooorm/dictionaries commit 8cfea406b505e4d7df52d5a19bce525df98c54ab,
dictionaries/en and dictionaries/en-GB (SCOWL size 60). Save index.aff as en.aff,
and the two index.dic files as en.dic and en-GB.dic in the input directory.
Both dictionaries use identical affixes. Licenses live beside the generated file.
Usage: python scripts/build-word-chain-dictionary.py SOURCE_DIRECTORY
"""
import base64
import hashlib
import json
from pathlib import Path
import re
import sys
import zlib

source = Path(sys.argv[1])
expected_blobs = {
    'en.aff': '9e7cb1e2f1c2cc3faff5a7ae2d5c041091017bdb',
    'en.dic': 'b41fd203e6daf76934db99dec6572a230516368a',
    'en-GB.dic': '85edde560296b643498da7292eabd09740682dd8',
}
for filename, expected in expected_blobs.items():
    data = (source / filename).read_bytes()
    actual = hashlib.sha1(b'blob ' + str(len(data)).encode() + b'\0' + data).hexdigest()
    assert actual == expected, f'{filename} does not match the pinned upstream source'
rules = {"PFX": {}, "SFX": {}}
affix = (source / 'en.aff').read_text()
for line in affix.splitlines():
    parts = line.split()
    if not parts or parts[0] not in rules:
        continue
    kind, flag = parts[:2]
    if len(parts) == 4:
        rules[kind][flag] = {"cross": parts[2] == 'Y', "rules": []}
    else:
        assert len(parts) == 5, f'Unsupported affix rule: {line}'
        strip, add, condition = parts[2:]
        assert '/' not in add, 'Continuation flags require a generator update'
        rules[kind][flag]['rules'].append((strip if strip != '0' else '', add if add != '0' else '', condition))
# This generator deliberately does not join words or expand ordinal compounds.
assert not re.search(r'^(?:NEEDAFFIX|CIRCUMFIX|FORBIDDENWORD|COMPLEXPREFIXES|FLAG)\b', affix, re.M)

def apply(word, kind, rule):
    strip, add, condition = rule
    if not re.search(('^' + condition) if kind == 'PFX' else (condition + '$'), word):
        return None
    if strip and not (word.startswith(strip) if kind == 'PFX' else word.endswith(strip)):
        return None
    if kind == 'PFX':
        return add + word[len(strip):]
    return (word[:-len(strip)] if strip else word) + add

words = set()
for filename in ['en.dic', 'en-GB.dic']:
    for line in (source / filename).read_text().splitlines()[1:]:
        if not line.strip():
            continue
        entry = line.split()[0]
        root, _, flags = entry.partition('/')
        if not re.fullmatch('[a-zA-Z]+', root) or 'c' in flags:
            continue
        assert all(flag in rules['PFX'] or flag in rules['SFX'] or flag == '!' for flag in flags), entry
        forms = {root}
        for flag in flags:
            for kind in rules:
                for rule in rules[kind].get(flag, {}).get('rules', []):
                    value = apply(root, kind, rule)
                    if value:
                        forms.add(value)
        for suffix in [rules['SFX'][flag] for flag in flags if flag in rules['SFX'] and rules['SFX'][flag]['cross']]:
            for suffix_rule in suffix['rules']:
                suffixed = apply(root, 'SFX', suffix_rule)
                if not suffixed:
                    continue
                for prefix in [rules['PFX'][flag] for flag in flags if flag in rules['PFX'] and rules['PFX'][flag]['cross']]:
                    for prefix_rule in prefix['rules']:
                        value = apply(suffixed, 'PFX', prefix_rule)
                        if value:
                            forms.add(value)
        words.update(word.lower() for word in forms if re.fullmatch('[a-zA-Z]{3,40}', word))

plain = '\n'.join(sorted(words)).encode()
encoded = base64.b64encode(zlib.compress(plain, 9)).decode()
target = Path(__file__).resolve().parents[1] / 'src/lib/word-chain-english-data.ts'
target.write_text('// Generated by scripts/build-word-chain-dictionary.py. See word-chain-english-LICENSE.txt.\n'
                  + f'// {len(words)} words; expanded list SHA-256: {hashlib.sha256(plain).hexdigest()}\n'
                  + 'export const WORD_CHAIN_ENGLISH_DATA = ' + json.dumps(encoded) + ';\n')
print(f'Generated {len(words)} single words ({len(encoded)} encoded bytes).')
